config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :logout
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ngos, only: %i[index show new create]
  resources :publications, only: %i[index show]
  get '/publications/:publication_id/create_offer', to: 'offers#create_offer', as: :create_offer

  resources :offers, only: %i[index show update] do
    resources :messages, only: %i[create]
  end

  resources :reports, only: %i[create]

  namespace :admin do
    resources :ngos, only: [:show] do
      resources :publications, only: %i[new create]
      resources :ngo_members, only: %i[new create]
    end

   resources :publications, only: %i[edit update destroy]
   resources :ngo_members, only: %i[destroy]
  end

  resources :pictures, only: %i[create destroy]
end

app/models/ngo_member.rb
class NgoMember < ApplicationRecord
  belongs_to :user
  belongs_to :ngo
  validates :user_id, :ngo_id, presence: true
end

app/controllers/admin/ngo_members_controller.rb
class Admin::NgoMembersController < ApplicationController
  before_action :set_ngo, only: %i[create]

  def create
    @ngo_member = NgoMember.new(ngo_member_params)
    @ngo_member.ngo = @ngo
    if @ngo_member.save
      respond_to do |format|
        format.html { redirect_to ngos_path(@ngo) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'admin/ngo_members/new' }
        format.js
      end
    end
  end

  def destroy
    @ngo_member = NgoMember.find(params[:id])
    @ngo_member.destroy
  end

  private

  def set_ngo
    @ngo = Ngo.find(params[:ngo_id])
  end

  def ngo_member_params
    params.require(:ngo_member).permit(:user_id)
  end
end

app/views/admin/ngo_members/_ngo_member_item.html.erb
<div id="ngo-member-<%= ngo_member.id %>" class="ngo-member">
  <%= ngo_member.user.first_name %>
  <% if @ngo.user == current_user %>
  <%= link_to admin_ngo_member_path(ngo_member), method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
    <i class="fas fa-trash-alt"></i>
    <% end %>
  <% end %>
</div>

app/views/admin/ngo_members/create.js.erb
function refreshForm(innerHTML) {
  var newNgoMemberForm = document.getElementById('new_ngo_member');
  newNgoMemberForm.innerHTML = innerHTML;
}

function addNgoMember(NgoMemberHTML) {
  var members = document.getElementById('ngo-members');
  var closeAddMemberModal =  document.getElementById('close-add-member-modal');
  members.insertAdjacentHTML('beforeend', NgoMemberHTML);
  closeAddMemberModal.click()
}

<% if @ngo_member.errors.any? %>
  refreshForm('<%= j render "/admin/ngos/ngo_members_form", ngo: @ngo, ngo_member: @ngo_member %>');
<% else %>
  addNgoMember('<%= j render "admin/ngo_members/ngo_member_item", ngo_member: @ngo_member %>');
  refreshForm('<%= j render "/admin/ngos/ngo_members_form", ngo: @ngo, ngo_member: NgoMember.new %>');
<% end %>

app/views/admin/ngo_members/destroy.js.erb
var ngoMember = document.getElementById("ngo-member-<%= @ngo_member.id %>")
ngoMember.remove()