config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :logout
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ngos, only: %i[index show new create]
  resources :publications, only: %i[index show]
  get '/publications/:publication_id/create_offer', to: 'offers#create_offer', as: :create_offer

  resources :offers, only: %i[index show update] do
    resources :messages, only: %i[create]
  end

  resources :reports, only: %i[create]

  namespace :admin do
    resources :ngos, only: [:show] do
      resources :publications, only: %i[new create]
      resources :ngo_members, only: %i[new create]
    end

   resources :publications, only: %i[edit update destroy]
   resources :ngo_members, only: %i[destroy]
  end

  resources :pictures, only: %i[create destroy]
end

app/models/publication.rb
class Publication < ApplicationRecord
  STATUS = { open: 0, closed: 1, archived: 2 }
  enum status: STATUS

  belongs_to :ngo
  belongs_to :category

  has_many :offers, dependent: :destroy
  has_many :offers_as_owner, dependent: :destroy, foreign_key: 'publication_id', class_name: 'Offer'
  has_many :offers_as_collaborator, dependent: :destroy, foreign_key: 'publication_id', class_name: 'Offer'

  has_many :pictures, as: :imageable
  
  validates :ngo_id, :title, :description, :intended_use, :category_id, :location, presence: true
  validates :description, :intended_use, length: { minimum: 10 }
  
  geocoded_by :location
  accepts_nested_attributes_for :pictures

  # after_create :send_notification_email
  after_validation :geocode, if: :will_save_change_to_location?
  
  include PgSearch::Model

  pg_search_scope :search_publications,
    against: {
      title: 'A',
      description: 'B',
      intended_use: 'B',
      location: 'C'
    },
    using: {
      tsearch: { prefix: true }
    }

  def send_notification_email
    PublicationMailer.with(publication: self).notification.deliver_later
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < ApplicationController
  before_action :set_ngo, only: %i[new create]
  before_action :set_publication, only: %i[edit update]

  before_action :set_categories, only: %i[new edit create update]

  def new
    @publication = Publication.new
    @publication.pictures.build
    authorize([:admin, @publication])
  end

  def create
    @publication = Publication.new(publication_params)
    if @publication.pictures.last.picture.file.nil?
      @publication.pictures.first.destroy
    else
      @publication.pictures.first.imageable_id = 1
    end
    @publication.ngo = @ngo
    authorize([:admin, @publication])
    if @publication.save
      redirect_to @publication
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @publication.update(publication_params)
      redirect_to @publication
    else
      render :new
    end
  end

  private

  def set_ngo
    @ngo = Ngo.find(params[:ngo_id])
  end

  def set_categories
    @categories = Category.roots
  end

  def set_publication
    @publication = Publication.find(params[:id])
  end

  def publication_params
    params.require(:publication).permit(
      :title,
      :description,
      :intended_use,
      :category_id,
      :subcategory,
      :location,
      :created_at,
      :updated_at,
      :closing_text,
      pictures_attributes: %i[
        picture
        imageable_id
        imageable_type
        category
      ]
    )
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @categories = Category.roots
    if params[:search].present?
      @publications = policy_scope(Publication).search_publications(params[:search])
      @markers = @publications.map do |publication|
        {
          lat: publication.latitude,
          lng: publication.longitude
        }
      end
      
    elsif params[:publication].present?
      @publications = policy_scope(Publication).all
      
      search = params[:publication][:search]
      status = params[:publication][:status]
      category_id = params[:publication][:category_id]
      location = params[:publication][:location]
      parent_category = params[:publication][:parent_category]
      return  @publications = @publications.select { |pub| parent_category.split("-").include?(pub.category.id.to_s) } if parent_category.present?

      @publications = @publications.search_publications(params[:publication][:search]) if search.present?
      @publications = @publications.where(status: status.to_i) if status.present?
      @publications = @publications.where(category_id: category_id.to_i) if category_id.present?
      @publications = @publications.near(location, 10) if location.present?
    else
      @publications = policy_scope(Publication).geocoded
      @markers = @publications.map do |publication|
        {
          lat: publication.latitude,
          lng: publication.longitude
        }
      end
    end
  end
  
  def show
    @picture = Picture.new
    @markers = [@publication].map do |_publication|
      {
        lat: @publication.latitude,
        lng: @publication.longitude
      }
    end
  end
  
  private
  
  def set_publication
    @publication = Publication.find(params[:id])
    authorize @publication
  end
end

app/views/publications/_closing_form.html.erb
<div class="modal fade" id="closingModal-<%= publication.id %>"  tabindex="-1" role="dialog" aria-labelledby="reportModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Close publication with evidence</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [:admin, publication] do |f| %>
          <%= f.input :closing_text %>
          <%= f.simple_fields_for :pictures, picture do |pf| %>
            <%= pf.input :picture, as: :file, required: true %>
            <%= pf.input :picture_cache, as: :hidden %>
            <%= pf.input :imageable_id, as: :hidden, input_html: { value: publication.id }  %>
            <%= pf.input :imageable_type, as: :hidden, input_html: { value: publication.class }  %>
            <%= pf.input :category, as: :hidden, input_html: { value: 'closing' } %>
          <% end %>
          <%= f.submit 'Upload evidence',class:'button', id: 'closingSubmit'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/publications/_form.html.erb
<%= simple_form_for @ngo do |f| %>
 <%= f.error_notification %>
 <%= f.input :title, placeholder: "10 chairs"%>
 <%= f.input :location, label: "Location", input_html: { id: 'ngo_address'}, placeholder: "1 Devonshire St, London W1W 5DR" %>
 <%= f.input :description, label: "Description", placeholder: "We need 10 chairs for donating to school" %>
  <%= f.input :category, label: "Category", placeholder: "category" %>
  <%= f.input :subcategory, label: "subcategory", placeholder: "subcategory" %>
 <%= f.simple_fields_for :pictures do |pf| %>
   <%= pf.input :picture, as: :file %>
   <%= pf.input :picture_cache, as: :hidden %>
   <%= pf.input :imageable_id, as: :hidden %>
   <%= pf.input :imageable_type, as: :hidden %>
 <% end %>
 <%= f.button :submit, class: "btn btn-success btn-lg"%>
<% end %>

app/views/publications/_offer_modal.html.erb
<div class="modal fade" id="offerModal" tabindex="-1" role="dialog" aria-labelledby="offerModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Thank you for your interest!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Thank you for making an offer.</p>
        <p>Now you will chat directly to the NGO</p>
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= link_to 'I can help', create_offer_path(@publication.id), class:"button" %>
      </div>
    </div>
  </div>
</div>

app/views/publications/index.html.erb
<div class="container my-5">
  <div class="row mt-5">
    <div class="col-3 px-4">
      <%= simple_form_for :publication, url: publications_path, method: :get do |f| %>
      <% if params[:search] %>
        <%= f.input :search, as: :hidden, input_html: { value: params[:search]}%>
      <% else %>
        <%= f.input :search, as: :hidden, input_html: { value: params[:publication][:search]}%>
      <% end %>
      <%= f.input :status, label: "Status", collection: Publication::STATUS.except(:archived)  %>
      <%= f.input :location, label: "Location", input_html: { id: 'ngo_address'}%>
      <%= f.input :category_id,
          as: :grouped_select,
          collection: @categories,
          group_method: :children
      %>
      <%= f.button :submit, 'Filter', class: "button"%>
      <% end %>
    </div>
    <div class="col-9">
      <% @publications.each do |pub| %>
        <%= link_to publication_path(pub) do  %>
          <div class="card-product pl-2 mt-3 <%= case pub.category.parent.name
                                          when 'Donate' then 'top-clean'
                                          when 'Goods' then 'top-butter'
                                          when 'Services' then 'top-salmon'
                                          end
                                           %> link">
            <div>
                <% if pub.pictures.reject { |p| p.category == 'closing' }.empty? %>
                  <div class="align-items-center justify-content-center d-flex" style="width: 120px; height: 100%;">
                    <%= cl_image_tag(Picture
                    .find_by(imageable_type: 'Ngo', imageable_id: pub.ngo.id, category: 'logo')
                    .picture,width: 120, height: 120, crop: 'fit') %>
                  </div>
                <% else %>
                   <div class="align-items-center justify-content-center d-flex" style="width: 120px; height: 100%;">
                    <%= cl_image_tag(Picture
                    .find_by(imageable_type: 'Publication', imageable_id: pub.pictures.first.id)
                    .picture, width: 120, height: 120, crop: 'fit') %>
                  </div>
                <% end %>
            </div>
            <div class="card-product-infos" style="max-width: 600px">
              <h2><%= pub.title %></h2>
              <p><%= pub.description[0..150]%>...</p>
            </div>
            <div class="card-product-infos">
              <div class="tag-category">
              <p class="text-center"> <%= pub.category.name %></p>
              </div>
              <% if pub.offers.empty? %>
                <small>Be the fist one to help this amazing people</small>
              <% else %>
                <small> <%= pub.offers.count %> users are already helping! Join them!</small>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/publications/show.html.erb
<%= content_for(:meta_og) do %>
  <meta property="og:title" content="<%= "#{@publication.ngo.name.capitalize} needs help with: #{@publication.title}" %> />
  <meta property="og:type" content="article" />
  <%# <meta property="og:published_time" content="<%= @publication.publication_date.strftime('%Y-%m-%d %H:%M') %>
  <meta property="og:author" content="mantaplatform.com" />
  <meta property="og:description" content="<%= truncate(@publication.description, length: 50) %>" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <% if @publication.ngo.pictures.first.present? %>
      <%= tag :meta, property: 'og:image', content: "#{cl_image_path(Picture.find_by(imageable_type: 'Ngo', imageable_id: @publication.ngo.id, category: 'logo').picture, width: 1200, height: 630, crop: :fit)}" %>
      <%= tag :meta, name: 'twitter:image:src', content: "#{cl_image_path(Picture.find_by(imageable_type: 'Ngo', imageable_id: @publication.ngo.id, category: 'logo').picture, width: 440, height: 220, crop: :fit)}" %>
  <% end %>
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="mantaplatform.com">
  <%# TODO add twitter account %>
  <%# <meta name="twitter:creator" content="@iedamarcondes"> %>
  <meta name="twitter:title" content="<%= "#{@publication.ngo.name.capitalize} needs help with: #{@publication.title}" %>" />
  <%# <meta name="twitter:site" content="<%= @publication.ngo.name %>
  <meta name="twitter:description" content="<%= truncate(@publication.description, length: 100) %>" />
<% end %>


<div class="container pub-style <%= case @publication.category.parent.name
                          when 'Donate' then 'bt-clean'
                          when 'Goods' then 'bt-butter'
                          when 'Services' then 'bt-salmon'
                          end %>">
  <div class="row">
    <div class="col-sm-12 col-md-4 py-4 d-flex flex-column align-items-center">
      <% if @publication.pictures.reject { |p| p.category == 'closing' }.empty? %>
        <div class="align-items-center justify-content-center d-flex" style="width: 300px; height: 365px;">
          <%= cl_image_tag(Picture
          .find_by(imageable_type: 'Ngo', imageable_id: @publication.ngo.id, category: 'logo')
          .picture, width: 300, height: 365, crop: 'fit') %>
        </div>
      <% else %>
        <div id="carouselExampleControls" class="carousel slide mb-5" data-ride="carousel">
          <div class="carousel-inner">
            <% @publication.pictures.reject { |p| p.category == 'closing' }.each_with_index do |pic, i| %>
                <% if i == 0 %>
                  <div class="carousel-item active">
                <% else %>
                  <div class="carousel-item">
                <% end %>
                    <%= cl_image_tag pic.picture, width: 300, height: 365, crop: 'fit', class: "d-block" %>
                  </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>
      <div
        id="map"
        style="width: 300px; height: 300px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        class="my-5"
      ></div>
      <div>
        <p class="sub-header mb-3">Share this pub on social media</p>
        <div class="text-center mb-3">
          <%= social_share_button_tag("#{@publication.ngo.name.capitalize} needs help with: #{@publication.title}") %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-8">
      <div class="d-flex justify-content-between align-items-center pb-3">
        <h2> <%= @publication.title %> </h2>
        <%= social_share_button_tag("#{@publication.ngo.name.capitalize} needs help with: #{@publication.title}") %>
        <%# <a href="#" class="btn btn-success">Share on SM</a> %>
      </div>
      <p>posted by <strong><%= link_to @publication.ngo.name, ngo_path(@publication.ngo),style: 'color:#D98D7C'  %></strong></p>
      <p><strong>Location: <%= @publication.location %></strong></p>
      <h3 class="sub-header">Description</h3>
      <p class="pb-3">
        <%= @publication.description %>
      </p>
      <h3 class="sub-header">Intended use</h3>
      <p class="pb-3">
        <%= @publication.intended_use %>
      </p>
      <% if @publication.closing_text %>
        <h3 class="sub-header">Closing</h3>
        <div class="text-center">
          <%= cl_image_tag Picture.find_by(imageable_type: @publication.class.to_s, imageable_id: @publication.id, category: 'closing').picture, width: 400, height: 300, crop: :fit %>
        </div>
        <h5>Closing evidence description</h5>
        <p>
          <%= @publication.closing_text %>
        </p>
      <% else %>
        <% if @publication.ngo.is_stakeholder?(current_user) %>
          <div class="my-5">
            <button type="button" class="btn btn-block" style="background-color:#55B8A9" data-toggle="modal" data-target="#closingModal-<%= @publication.id%>">
              Upload evidence
            </button>
          </div>
          <%= render 'publications/closing_form', publication: @publication, picture: @picture %>
        <% else %>
          <div class="my-5">
            <button type="button" class="btn btn-block" style="background-color:
            #55B8A9" data-toggle="modal" data-target="#offerModal">
              I can help!
            </button>
          </div>
        <% end %>
      <% end %>
      <% if @publication.ngo.publications.count > 1 %>
        <hr>
        <h5 class="sub-header">Other publications by <%= @publication.ngo.name.capitalize %></h3>
        <ul>
          <% @publication.ngo.publications.reject { |p| p.id == @publication.id }.last(5).each do |pub| %>
            <li>
              <strong><%= link_to pub.title, pub, class: 'link' %></strong>
            </li>
          <% end %>
        </ul>
      <% end %>
      <hr>
      <h5 class="sub-header">Other publications in this category</h3>
      <ul>
        <% @publication.category.publications.reject { |p| p.id == @publication.id }.last(5).each do |pub| %>
          <li>
            <strong><%= link_to pub.title, pub, class: 'link' %></strong> posted by <strong><%= link_to pub.ngo.name, pub.ngo, style: 'color:#D98D7C' %></strong>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<%= render 'offer_modal' %>