config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :logout
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ngos, only: %i[index show new create]
  resources :publications, only: %i[index show]
  get '/publications/:publication_id/create_offer', to: 'offers#create_offer', as: :create_offer

  resources :offers, only: %i[index show update] do
    resources :messages, only: %i[create]
  end

  resources :reports, only: %i[create]

  namespace :admin do
    resources :ngos, only: [:show] do
      resources :publications, only: %i[new create]
      resources :ngo_members, only: %i[new create]
    end

   resources :publications, only: %i[edit update destroy]
   resources :ngo_members, only: %i[destroy]
  end

  resources :pictures, only: %i[create destroy]
end

app/views/shared/_banner.html.erb
<div class="home-banner">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="d-block w-100 banner-img word" style="background-image:url(<%= asset_path('banner_1') %>);">
      </div>
    </div>
    <div class="carousel-item">
      <div class="d-block w-100 banner-img" style="background-image: url(<%= asset_path('banner_2') %>);"></div>
    </div>
    <div class="carousel-item">
      <div class="d-block w-100 banner-img" style="background-image: url(<%= asset_path('banner_3')%>"></div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Site footer -->
  <footer class="site-footer mt-5">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-4 col-lg-4">
        <h6>About MANTA</h6>
         <p class="text-justify">MANTA is a plateform to channel the goodwill</p>
        </div>

        <div class="col-12 col-md-8 col-lg-8">
           <div><%=render "shared/mailinglist" %></div>
           <div class="box-info d-flex align-items-top">
            <div>
              <ul class="footer-links mr-5">
               <h6>ABOUT US</h6>
               <li><a href="#">Our team</a></li>
               <li><a href="#">Our impact</a></li>
               <li><a href="#">Our policy</a></li>
               <li><a href="#">Contact us</a></li>
              </ul>
            </div>
            <div>
              <h6>MADE BY</h6>
                <ul class="footer-links">
                  <li><a class="fab fa-github" href="https://github.com/fesilvajacquier"> Fer </a></li>
                  <li><a class="fab fa-github" href="https://github.com/pinplengpai"> Pin</a></li>
                  <li><a class="fab fa-github" href="https://github.com/YUYUMO"> Yuyu </a></li>
                  <li><a class="fab fa-github" href="https://github.com/Orpere"> Orlando </a></li>
                  <li>with<i class="fas fa-heart"></i></li>
                  <li>at <a href="https://www.lewagon.com">le wagon</a></li>
                </ul>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>

app/views/shared/_js_flashes.html.erb
<div id="js_flashes">
</div>

app/views/shared/_mailinglist.html.erb
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background: none; clear:left; font:14px, Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://gmail.us3.list-manage.com/subscribe/post?u=8a1adea58c79aa0f51e638ae7&amp;id=6c8860f0c0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div>
    <div id="mc_embed_signup_scroll">

      <div class="d-flex">
        <div style="width: 70%;" class="">
    	   <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" style="width: 100%; height: 35px; border-top-right-radius: 0; border-bottom-right-radius: 0;">
        </div>
        <div>
          <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button" style="height: 35px; border-top-left-radius: 0; border-bottom-left-radius: 0; background-color:#55B8A9;" >
        </div>
      </div>

  	  <div id="mce-responses" class="clear">
  		  <div class="response" id="mce-error-response" style="display:none"></div>
  		  <div class="response" id="mce-success-response" style="display:none"></div>
  	  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div hidden aria-hidden="true"><input type="text" name="b_8a1adea58c79aa0f51e638ae7_6c8860f0c0" tabindex="-1" value="">
      </div>
    </div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag asset_path("manta.png") %>
<% end %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

  <form id="search-form" class="form-inline d-none d-md-block mr-auto" action="/publications">
    <div class="search-navbar d-flex">

      <select id="search-categories">
        <option value="ngos">NGOs</option>
        <option value="publications" selected>Publications</option>
      </select>

      <input class="form-control mr-sm-2" type="text" name="search" placeholder="Try teach coding" aria-label="Search">
                        <i class="fas fa-search"></i>

    </div>

  </form>


<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Add NGO", new_ngo_path, class: "nav-link mr-5" %>
    </li>
    <li class="nav-item dropdown">
      <% if signed_in? %>
        <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "https://cdn.head-fi.org/g/2283245_l.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if signed_in? %>
        <% if current_user.last_offer %>
          <%= link_to "My offers", offer_path(current_user.last_offer), class: "dropdown-item" %>
        <% end %>
          <% unless current_user.ngos_as_owner.empty? %>
            <span class="dropdown-item">My NGOs</span>
            <% current_user.ngos_as_owner.each do |ngo| %>
              <%= link_to "> #{ngo.name.capitalize}", admin_ngo_path(ngo), class: "dropdown-item" %>
            <% end %>
          <% end %>
          <% unless current_user.ngos_as_collaborator.empty? %>
            <span class="dropdown-item">My NGOs as a collaborator</span>
            <% current_user.ngos_as_collaborator.each do |ngo| %>
              <%= link_to "> #{ngo.name.capitalize}", admin_ngo_path(ngo), class: "dropdown-item" %>
            <% end %>
          <% end %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
            <%= link_to "Sign in", user_session_path, class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
  </ul>
</div>
</div>