config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  delete 'sign_out', :to => 'devise/sessions#destroy', :as => :logout
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ngos, only: %i[index show new create]
  resources :publications, only: %i[index show]
  get '/publications/:publication_id/create_offer', to: 'offers#create_offer', as: :create_offer

  resources :offers, only: %i[index show update] do
    resources :messages, only: %i[create]
  end

  resources :reports, only: %i[create]

  namespace :admin do
    resources :ngos, only: [:show] do
      resources :publications, only: %i[new create]
      resources :ngo_members, only: %i[new create]
    end

   resources :publications, only: %i[edit update destroy]
   resources :ngo_members, only: %i[destroy]
  end

  resources :pictures, only: %i[create destroy]
end

app/models/ngo.rb
class Ngo < ApplicationRecord
  belongs_to :user

  has_many :publications, dependent: :destroy
  has_many :publications_as_owner, dependent: :destroy, foreign_key: 'ngo_id', class_name: 'Publication'
  has_many :publications_as_collaborator, dependent: :destroy, foreign_key: 'ngo_id', class_name: 'Publication'

  has_many :offers, through: :publications
  has_many :reports, dependent: :destroy
  has_many :ngo_members, dependent: :destroy
  has_many :users, through: :ngo_members
  has_many :pictures, as: :imageable, dependent: :destroy
  validates :name, :address, :email, :website, :description, :bank_account, :user_id, presence: true

  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :website, format: { with: %r{[(http(s)?)://(www\.)?a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)} }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  accepts_nested_attributes_for :pictures

  include PgSearch::Model
  pg_search_scope :search_ngos,
                  against: {
                    name: 'A',
                    description: 'B',
                    address: 'C'
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def is_stakeholder?(current_user)
    current_user == user || users.include?(current_user)
  end
end

app/controllers/admin/ngos_controller.rb
class Admin::NgosController < ApplicationController
  def show
    @picture = Picture.new
    @ngo = Ngo.find(params[:id])
    @ngo_member = NgoMember.new
    @ngo_members = @ngo.ngo_members
    authorize([:admin, @ngo])
  end
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController
  before_action :set_ngo, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[show]

  def index
    if params[:search].present?
      @ngos = policy_scope(Ngo).search_ngos(params[:search])
    else
      @ngos = policy_scope(Ngo).geocoded # returns flats with coordinates
      @markers = @ngos.map do |ngo|
        {
          lat: ngo.latitude,
          lng: ngo.longitude
        }
      end
    end
  end

  def show
    @report = Report.new
    @ngos = Ngo.find(params[:id])

    @markers = [@ngos].map do |_ngo|
      {
        lat: @ngo.latitude,
        lng: @ngo.longitude
      }
    end
  end

  def new
    @ngo = Ngo.new
    @ngo.pictures.build
    authorize @ngo
  end

  def create
    # raise
    @ngo = Ngo.new(ngo_params)
    @ngo.pictures.first.imageable_id = 1
    @ngo.pictures.first.category = 'logo'
    @ngo.user = current_user
    authorize @ngo
    if @ngo.save
      redirect_to ngo_path(@ngo)
    else
      render :new
    end
  end

  private

  def ngo_params
    params.require(:ngo).permit(
      :name,
      :address,
      :email,
      :website,
      :description,
      :bank_account,
      :user_id,
      :created_at,
      :updated_at,
      pictures_attributes: %i[
        picture
        imageable_id
        imageable_type
      ]
    )
  end

  def set_ngo
    @ngo = Ngo.find(params[:id])
    authorize @ngo
  end
end

app/views/admin/ngos/_ngo_members_form.html.erb
<%= simple_form_for([:admin, ngo, ngo_member], remote: true) do |form| %>
  <%= form.input :user_id, label: :user, collection: User.all.map { |u| [u.email, u.id] } %>
  <%= form.submit class: "button"%>
<% end %>

app/views/admin/ngos/show.html.erb
<div class="container">
  <h1 style="font-size:30px">Manage my publication</h1>

<div class="d-flex align-items-top offers-display">
  <div class="offers-wrapper">
    <% @ngo.publications.each do |pub| %>
        <div class="card-product mt-3 <%= case pub.category.parent.name
                                          when 'Donate' then 'top-clean'
                                          when 'Goods' then 'top-butter'
                                          when 'Services' then 'top-salmon'
                                          end
                                           %>">
       <%= link_to publication_path(pub) do  %>
          <div class="card-product-infos">
            <h2><%= pub.title %></h2>
            <p><%= pub.description[0..150] %> ...</p>
            <% if pub.offers.empty? %>
              <p><i class="fas fa-hand-holding-heart"></i> No offer</p>
            <% else %>
              <p> <i class="fas fa-hand-holding-heart"></i> <%= link_to "#{pub.offers.count} offer(s)",offer_path(pub.offers.last) %></p>
            <% end %>
          </div>
          <div>
           <%= link_to "Edit", edit_admin_publication_path(pub), class:"button" %>
            <div class="report-ngo-button mt-2">
              <button type="button" class="button" style="font-size:12px" data-toggle="modal" data-target="#closingModal-<%= pub.id %>">
                Upload evidence
              </button>
            </div>
            <%= render 'publications/closing_form', publication: pub, picture: @picture %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="user-options aling-items-center text-center mt-3">

    <%= link_to "See offers", offers_path(@publication), class:"button" %>
    <%= link_to "My profile", @ngo, class:"button" %>
    <%= link_to "Create publication", new_admin_ngo_publication_path(@ngo), class:"button"%>
      <%# unless @ngo.ngo_members.empty? %>
        <div class="ngo-members mt-3">
          <% if @ngo.user == current_user %>
            <p><%= @ngo.name.capitalize %> member(s)</p>
            <div id="ngo-members" class="mb-3">
              <% @ngo_members.each do |ngo_member| %>
              <%= render 'admin/ngo_members/ngo_member_item', ngo_member: ngo_member %>
              <% end %>
            </div>
          <% end %>
        </div>
      <%# end %>
  <% if @ngo.user == current_user %>
    <button type="button" class="button" style="font-size:12px" data-toggle="modal" data-target="#ngo-member-modal">
    Add members
    </button>
    <% end %>
  <% if @ngo.user == current_user %>
<div class="modal fade" id="ngo-member-modal" tabindex="-1" role="dialog" aria-labelledby="reportModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add a new member of your NGO</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close-add-member-modal">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'ngo_members_form', ngo: @ngo, ngo_member: @ngo_member %>
        </div>
      </div>
    </div>
  </div>
  </div>
<% end %>
</div>
</div>
</div>